import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import { FaAngleRight } from "react-icons/fa";
import { FaUserDoctor } from "react-icons/fa6";
import { FaCheck } from "react-icons/fa";
import { FaFlask } from "react-icons/fa";
import { FaBaby } from "react-icons/fa6";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div class="hero v-center about-inside pr">
          <div class="overlay-inside"></div>
          <div class="wrapper box-center jcs pr zi2">
            <div class="about-hero tac">
              <h1 class="fs38 fw7 mt8 fs30 fw7 lh24 fc4 mb32">About Us</h1>
              <ul class="df ttu box-center fc4">
                <li class="v-center mr16 fs14">
                  <Link href="/" previewlistener="true">
                    HOME
                  </Link>
                </li>
                <li>
                  <FaAngleRight />
                </li>
                <li class="v-center fs14 ml16">About</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="wrapper  pb64">
          <div class="df mt32">
            <div class="flx48 mr24">
              <img
                src="/images/about-img.jpg"
                layout="responsive"
                alt="delivery-inside image"
                className="mtb24 w100"
              />
            </div>
            <div class="ptb48 pl48">
              <div class="about-content">
                <span class="fs18 fc1 fw6 ">About Us</span>
                <h2 class="fs36 fw6 ptb24 lh48">
                  Short Story About Fovia Clinic Since 1999
                </h2>
                <p class="lh30 v-center fc3 fs18 ">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Quis ipsum suspendisse ultrices gravida. Risus commodo viverra
                  maecenas accumsan lacus vel facilisis.
                </p>
                <ul class="lh30 pt24">
                  <li>
                    <FaCheck /> Scientific Skills For getting a better result
                  </li>
                  <li>
                    <FaCheck /> Communication Skills to getting in touch
                  </li>
                  <li>
                    <FaCheck /> A Career Overview opportunity Available
                  </li>
                  <li>
                    <FaCheck /> A good Work Environment For work
                  </li>
                  <li>
                    <FaCheck /> Scientific Skills For getting a better result
                  </li>
                  <li>
                    <FaCheck /> Communication Skills to getting in touch
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <section class="our-vision-area ptb-100 pt-0">
          <div class="wrapper">
            <div class="df mb48 ">
              <div class="col-lg-4 col-md-6 col-12">
                <div class="single-vision-box plr16">
                  <div class="fs36 fc1 pb16 ">
                    <FaCheck />
                  </div>
                  <h3 class="lh24 v-center fw7 fs22 pb16 ">Our Mission</h3>
                  <p class="lh30 v-center fc3 fs18 ">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Quis ipsum suspendisse.
                  </p>
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-12">
                <div class="single-vision-box plr16">
                  <div class="fs36 fc1 pb16">
                    <FaCheck />
                  </div>
                  <h3 class="lh24 v-center fw7 fs22 pb16 ">Our Mission</h3>
                  <p class="lh30 v-center fc3 fs18 ">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Quis ipsum suspendisse.
                  </p>
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-12">
                <div class="single-vision-box pl16">
                  <div class="fs36 fc1 pb16">
                    <FaCheck />
                  </div>
                  <h3 class="lh24 v-center fw7 fs22 pb16 ">Our Mission</h3>
                  <p class="lh30 v-center fc3 fs18 ">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Quis ipsum suspendisse.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <div class="wrapper  pb64">
          <div class="df mt32">
            <div class="ptb48 ">
              <div class="about-content">
                <span class="fs18 fc1 fw6 ">Our Mission & Vision</span>
                <h2 class="fs36 fw6 ptb24 lh48">
                  Better Information, Better Health
                </h2>
                <p class="lh30 v-center fc3 fs18 ">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
                <div class="df">
                  <ul class="lh30 pt24">
                    <FaUserDoctor class="fs26" />
                    <li>
                      PROFESSIONAL STAFF
                      <p>
                        Lorem ipsum dolor sit amet sit, consectetur adipiscing
                        elit.
                      </p>
                    </li>
                  </ul>
                  <ul class="lh30 pt24">
                    <FaFlask class="fs26" />
                    <li>
                      SUFFICIENT LAB TESTS
                      <p>
                        Lorem ipsum dolor sit amet sit, consectetur adipiscing
                        elit.
                      </p>
                    </li>
                  </ul>
                </div>
                <div class="df">
                  <ul class="lh30 pt24">
                    <FaBaby class="fs26" />
                    <li>
                      NEWBORN CARE
                      <p>
                        Lorem ipsum dolor sit amet sit, consectetur adipiscing
                        elit.
                      </p>
                    </li>
                  </ul>
                  <ul class="lh30 pt24">
                    <FaUserDoctor class="fs26" />
                    <li>
                      Delivery
                      <p>
                        Lorem ipsum dolor sit amet sit, consectetur adipiscing
                        elit.
                      </p>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="flx48 ">
              <img
                src="/images/mission-img.jpg"
                layout="responsive"
                alt="delivery-inside image"
                className="mtb24 w100"
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
