import Head from "next/head";
import { Inter } from "next/font/google";
import HeroSection from "@/components/HeroSection";
import AppointmentForm from "@/components/AppointmentForm";
import AboutSection from "@/components/AboutSection";
import ServiceSection from "@/components/ServiceSection";
import MedicalEmergency from "@/components/MedicalEmergency";
import FaqSection from "@/components/FaqSection";
import HowWeWork from "@/components/HowWeWork";
import DoctorTeam from "@/components/DoctorTeam";
import ContactUs from "@/components/ContactUs";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HeroSection />

      <main className='main'>
        <AppointmentForm />
        <AboutSection />
        <ServiceSection />
        <FaqSection />
        <HowWeWork />
        <MedicalEmergency />
        <DoctorTeam/>
        <ContactUs/>
      </main>
    </>
  );
}
